SELECT * FROM PLAYER;

-- PLAYER 테이블에서 TEAM_ID가 'K01'인 선수 검색
SELECT * FROM PLAYER WHERE TEAM_ID = 'K01';

-- PLAYER 테이블에서 TEAM_ID가 'K01'이 아닌 선수 검색
SELECT * FROM PLAYER WHERE TEAM_ID != 'K01';

-- PLAYER 테이블에서 WEIGHT가 70 이상이고 80 이하인 선수 검색
SELECT * FROM PLAYER WHERE WEIGHT >= 70 AND WEIGHT <= 80;

-- PLAYER 테이블에서 WEIGHT가 70 이상이고 80 이하인 선수 검색
SELECT * FROM PLAYER WHERE WEIGHT BETWEEN 70 AND 80;

-- PLAYER 테이블에서 TEAM_ID가 'K03'이고, HEIGHT가 180이하인 선수
SELECT * FROM PLAYER
WHERE TEAM_ID = 'K03' AND HEIGHT < 180;

-- PLAYER 테이블에서 TEAM_ID가 'K06'이고 KICKNAME이 '제리'인 선수 검색
SELECT * FROM PLAYER
WHERE TEAM_ID = 'K06' AND NICKNAME = '제리';

-- PLAYER 테이블에서 HEIGHT가 170이상이고 WEIGHT가 80 이상인 선수 이름 검색
SELECT * FROM PLAYER
WHERE HEIGHT >= 170 AND WEIGHT >= 80;

-- STADIUM 테이블에서 SEAT_COUNT가 3000초과이고 4100 이하인 경기장 검색
SELECT * FROM STADIUM
WHERE SEAT_COUNT > 30000 AND SEAT_COUNT <= 41000;

-- PLAYER 테이블에서 TEAM_ID가 'K02'이거나 'K07'이고 포지션은 'MF'인 선수 검색
-- 항상 OR 보다 AND가 우선순위가 높음
SELECT * FROM PLAYER
WHERE (TEAM_ID = 'K02' OR TEAM_ID = 'K07') AND "POSITION"  = 'MF';

SELECT * FROM PLAYER
WHERE TEAM_ID IN('K02', 'K07') AND "POSITION" = 'MF'; 

SELECT * FROM TEAM;