SELECT * FROM FLOWER;
-- 추가 : 부모와 자식 중 부모테이블에 먼저 값을 추가해야한다.
-- 삭제 : 부모와 자식 중 자식테이블에서 참조하는 값들을 먼저 삭제해야한다.
INSERT INTO FLOWER f 
(FLOWERNAME, FLOWERCOLOR, FLOWERPRICE)
VALUES('장미', 'RED', 3000);

INSERT INTO FLOWER f 
(FLOWERNAME, FLOWERCOLOR, FLOWERPRICE)
VALUES('해바라기', 'YELLOW', 5000);

INSERT INTO FLOWER f 
(FLOWERNAME, FLOWERCOLOR, FLOWERPRICE)
VALUES('할미꽃', 'WHITE', 9000);

DELETE FROM FLOWER
WHERE FLOWERNAME = '장미';

SELECT * FROM POT;

INSERT INTO POT
(POTID, POTCOLOR, POTSHAPE, NAME)
VALUES('20231224', 'WHITE', '원형', '장미');

INSERT INTO POT
(POTID, POTCOLOR, POTSHAPE, NAME)
VALUES('20231225', 'YELLOW', '타원형', '해바라기');

DELETE FROM POT
WHERE NAME = '장미';

-- DELETE 와 TRUNCATE
-- DELETE는 복구 가능
-- TRUNCATE는 복구 불가능

-- UPDATE
UPDATE POT 
SET POTCOLOR = 'WHITE'
WHERE NAME = '할미꽃' AND POTSHAPE = '타원형';