CREATE TABLE TBL_MEMBER(
	NAME VARCHAR2(500),
	AGE NUMBER
);

DROP TABLE TBL_MEMBER;

-- 제약조건 생성
CREATE TABLE TBL_CAR(
	ID NUMBER,
	BRAND VARCHAR2(100),
	COLOR VARCHAR2(100),
	PRICE NUMBER,
	CONSTRAINT CAR_PK PRIMARY KEY(ID)
);
-- 제약조건 삭제
ALTER TABLE TBL_CAR DROP CONSTRAINT CAR_PK;

-- 제약조건 추가
ALTER TABLE TBL_CAR ADD CONSTRAINT CAR_PK PRIMARY KEY(ID);

CREATE TABLE TBL_ANIMAL(
	ID NUMBER PRIMARY KEY,
	"TYPE" VARCHAR2(100),
	AGE NUMBER(3),
	FEED VARCHAR2(100)
);
-- 기존 제약조건 삭제
ALTER TABLE TBL_ANIMAL DROP CONSTRAINT SYS_C007543; -- 이 이름은 테이블 제거 생성때마다 바뀜
-- 제약조건 추가
ALTER TABLE TBL_ANIMAL ADD CONSTRAINT ANIMAL_PK PRIMARY KEY(ID);

DROP TABLE TBL_ANIMAL;
DROP TABLE TBL_CAR;
