/*
 *  OWNER
 *  ID VARCHAR2(100)
 * 	-----------
 * 	NAME VARCHAR2(200)
 * 	AGE NUMBER(5)
 * 	ADDRES VARCHAR2(300)
 * 
 * 	PET
 * 	PIN VARCHAR2(300)
 * 	------------
 * 	NAME VARCHAR2(200)
 * 	AGE NUMBER2(5)
 * 	ID VARCHAR2(200)
 * */

SELECT * FROM OWNER;

CREATE TABLE OWNER(
	ID VARCHAR2(200) PRIMARY KEY,
	NAME VARCHAR2(200) NOT NULL,
	AGE NUMBER(5) DEFAULT 20,
	ADDRESS VARCHAR2(300)
);
SELECT * FROM DDAZUAPET;
DROP TABLE DDAZUAPET;
CREATE TABLE DDAZUAPET(
	PIN VARCHAR2(300) PRIMARY KEY,
	NAME VARCHAR2(200) NOT NULL,
	AGE NUMBER(5) DEFAULT 1,
	OWNERID VARCHAR2(200),
	GENDER CHAR(1) DEFAULT 'M' NOT NULL CONSTRAINT CHECK_CHAR CHECK(GENDER IN('M', 'W')),
	CONSTRAINT DDAZUAPET_FK FOREIGN KEY(OWNERID) REFERENCES OWNER(ID)
);