CREATE TABLE TBL_MEMBER(
    NUM NUMBER PRIMARY KEY,
    NAME VARCHAR2(1000),
    BIRTHDAY DATE
);

SELECT * FROM TBL_MEMBER;

INSERT INTO TBL_MEMBER
VALUES(1, '이진원', TO_DATE('2001-02-05','YYYY-MM-DD'));