-- EMP테이블에서 사원번호 DEPT 테이블의 지역 검색하기
SELECT * FROM EMP; -- 자식
SELECT * FROM DEPT; -- 부모

SELECT EMP.DEPTNO, EMP.ENAME, EMP.JOB, DEPT.LOC FROM EMP JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

-- PLAYER테이블에서 송종국 선수가 속한 팀의 전화번호 검색하기
SELECT * FROM PLAYER;
SELECT * FROM TEAM;

SELECT p.TEAM_ID, p.PLAYER_NAME, t.TEL FROM PLAYER p JOIN TEAM t 
ON p.TEAM_ID = t.TEAM_ID AND p.PLAYER_NAME = '송종국';

-- JOBS테이블에서 JOB_ID로 EMPLOYEES의 JOB_TITLE, EMAIL, 성, 이름 검색
SELECT * FROM JOBS;
SELECT * FROM EMPLOYEES;

SELECT j.JOB_ID, j.JOB_TITLE, e.EMAIL, e.LAST_NAME ||' '|| e.FIRST_NAME 이름
FROM JOBS j JOIN EMPLOYEES e 
ON j.JOB_ID = e.JOB_ID;

-- 급여로 등급 나누기
SELECT * FROM SALGRADE s;
SELECT * FROM EMP e;
SELECT * FROM DEPT;

SELECT e.EMPNO , e.ENAME, s.GRADE, e.SAL FROM
SALGRADE s JOIN EMP e 
ON e.SAL BETWEEN s.LOSAL AND s.HISAL;

-- 표준문법
SELECT e.EMPNO , d.DNAME, e.ENAME, s.GRADE, e.SAL FROM
SALGRADE s JOIN EMP e 
ON e.SAL BETWEEN s.LOSAL AND s.HISAL
JOIN DEPT d
ON e.EMPNO = d.DEPTNO;

-- JOIN을 줄인 문법
SELECT e.EMPNO , d.DNAME, e.ENAME, s.GRADE, e.SAL FROM
SALGRADE s , EMP e , DEPT d
WHERE e.SAL BETWEEN s.LOSAL AND s.HISAL AND e.DEPTNO = d.DEPTNO;

